export const projects = [
  {
    id: "1",
    slug: "warm-apartment",
    title: { ru: "Светлая квартира", en: "Light Apartment" },
    shortDescription: { ru: "78 м² · Тёплый минимализм", en: "78 m² · Warm minimalism" },
    description: { ru: "Светлое жилое пространство в тёплых нейтральных тонах.", en: "A light residential space in warm neutral tones." },
    area: "78 м²",
    year: "2024",
    location: { ru: "Концепт", en: "Concept" },
    heroImage: "https://images.unsplash.com/photo-1600210492493-0946911123ea?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "2",
    slug: "open-plan-house",
    title: { ru: "Дом с открытой планировкой", en: "Open Plan House" },
    shortDescription: { ru: "240 м² · Пространство и свет", en: "240 m² · Space and light" },
    description: { ru: "Просторный дом с открытой планировкой и крупным остеклением.", en: "A spacious house with open planning and large glazing." },
    area: "240 м²",
    year: "2023",
    location: { ru: "Концепт", en: "Concept" },
    heroImage: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "3",
    slug: "soft-bedroom",
    title: { ru: "Спальня в мягких тонах", en: "Soft Bedroom" },
    shortDescription: { ru: "34 м² · Спокойная зона отдыха", en: "34 m² · Calm rest zone" },
    description: { ru: "Спокойное пространство для отдыха с мягким светом и нейтральной палитрой.", en: "A calm rest space with soft light and neutral palette." },
    area: "34 м²",
    year: "2024",
    location: { ru: "Концепт", en: "Concept" },
    heroImage: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "4",
    slug: "modern-house",
    title: { ru: "Современный дом", en: "Modern House" },
    shortDescription: { ru: "160 м² · Архитектура и природа", en: "160 m² · Architecture and nature" },
    description: { ru: "Современный дом с акцентом на архитектуру, свет и связь с природой.", en: "A modern house focused on architecture, light and nature." },
    area: "160 м²",
    year: "2022",
    location: { ru: "Концепт", en: "Concept" },
    heroImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1600&auto=format&fit=crop",
  },
];